-- ============================================================
-- HOOSIER_DATA RAW Layer — COPY INTO Commands
-- Run after uploading files to each stage
-- ============================================================

-- ── CAMPAIGN FINANCE ─────────────────────────────────────
-- Stage: CAMPAIGN_STAGE
-- Files: YYYY_ContributionData.csv (2018-2026)

COPY INTO HOOSIER_DATA.RAW.CAMPAIGN_FINANCE_SOURCE
FROM @HOOSIER_DATA.RAW.CAMPAIGN_STAGE
PATTERN = '.*ContributionData.*\.csv'
FILE_FORMAT = (
    TYPE = 'CSV'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    ENCODING = 'UTF-8'
    NULL_IF = ('')
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
)
ON_ERROR = 'CONTINUE';

-- ── LEGISCAN ─────────────────────────────────────────────
-- Stage: LEGISCAN_STAGE
-- Files: bills_YYYY.csv, votes_YYYY.csv, etc.

COPY INTO HOOSIER_DATA.RAW.LEGISCAN_BILLS
FROM @HOOSIER_DATA.RAW.LEGISCAN_STAGE
PATTERN = '.*bills.*\.csv'
FILE_FORMAT = (TYPE='CSV' SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"');

COPY INTO HOOSIER_DATA.RAW.LEGISCAN_PEOPLE
FROM @HOOSIER_DATA.RAW.LEGISCAN_STAGE
PATTERN = '.*people.*\.csv'
FILE_FORMAT = (TYPE='CSV' SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"');

COPY INTO HOOSIER_DATA.RAW.LEGISCAN_ROLLCALLS
FROM @HOOSIER_DATA.RAW.LEGISCAN_STAGE
PATTERN = '.*rollcalls.*\.csv'
FILE_FORMAT = (TYPE='CSV' SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"');

COPY INTO HOOSIER_DATA.RAW.LEGISCAN_VOTES
FROM @HOOSIER_DATA.RAW.LEGISCAN_STAGE
PATTERN = '.*votes.*\.csv'
FILE_FORMAT = (TYPE='CSV' SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"');

COPY INTO HOOSIER_DATA.RAW.LEGISCAN_SPONSORS
FROM @HOOSIER_DATA.RAW.LEGISCAN_STAGE
PATTERN = '.*sponsors.*\.csv'
FILE_FORMAT = (TYPE='CSV' SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"');

-- ── LOBBYING ─────────────────────────────────────────────
-- Stage: LOBBYING_STAGE
-- Files: employer_lobbyist_total_YYYY.csv, compensated_lobbyist_total_YYYY.csv

COPY INTO HOOSIER_DATA.RAW.LOBBYING_EMPLOYER
FROM @HOOSIER_DATA.RAW.LOBBYING_STAGE
PATTERN = '.*employer.*\.csv'
FILE_FORMAT = (TYPE='CSV' SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"'
    NULL_IF=('') ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE)
ON_ERROR = 'CONTINUE';

COPY INTO HOOSIER_DATA.RAW.LOBBYING_COMPENSATED
FROM @HOOSIER_DATA.RAW.LOBBYING_STAGE
PATTERN = '.*compensated.*\.csv'
FILE_FORMAT = (TYPE='CSV' SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"'
    NULL_IF=('') ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE)
ON_ERROR = 'CONTINUE';

-- ── STATE EXPENDITURES ────────────────────────────────────
-- Stage: EXPENDITURE_STAGE
-- Files: expenditure_YYYYqQ.csv (FY2020 Q1 through FY2026 Q2)

COPY INTO HOOSIER_DATA.RAW.STATE_EXPENDITURES
FROM @HOOSIER_DATA.RAW.EXPENDITURE_STAGE
PATTERN = '.*expenditure.*\.csv'
FILE_FORMAT = (TYPE='CSV' SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"'
    NULL_IF=(''))
ON_ERROR = 'CONTINUE';

-- ── VENDOR EXPENDITURES ───────────────────────────────────
-- Stage: VENDOR_STAGE
-- Files: vendor_YYYYqQ.csv

COPY INTO HOOSIER_DATA.RAW.VENDOR_EXPENDITURES
FROM @HOOSIER_DATA.RAW.VENDOR_STAGE
PATTERN = '.*vendor.*\.csv'
FILE_FORMAT = (TYPE='CSV' SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"'
    NULL_IF=(''))
ON_ERROR = 'CONTINUE';

-- ── GATEWAY LOCAL GOVERNMENT ──────────────────────────────
-- Stage: GATEWAY_STAGE
-- Note: pipe-delimited, not CSV

-- Year files (2020-2024) — 20 columns
COPY INTO HOOSIER_DATA.RAW.GATEWAY_DISBURSEMENTS
FROM @HOOSIER_DATA.RAW.GATEWAY_STAGE
PATTERN = '.*detailedDisburse_fundsNOdept_20.*\.txt'
FILE_FORMAT = (TYPE='CSV' FIELD_DELIMITER='|' SKIP_HEADER=1
    NULL_IF=('') ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE)
ON_ERROR = 'CONTINUE';

-- Legacy bulk file (17 columns, different schema)
COPY INTO HOOSIER_DATA.RAW.GATEWAY_DISBURSEMENTS_LEGACY
FROM @HOOSIER_DATA.RAW.GATEWAY_STAGE
PATTERN = '.*detailedDisburse_fundsNOdept_part.*\.txt'
FILE_FORMAT = (TYPE='CSV' FIELD_DELIMITER='|' SKIP_HEADER=1
    NULL_IF=('') ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE)
ON_ERROR = 'CONTINUE';

-- Year files (2021-2024) — 23 columns
COPY INTO HOOSIER_DATA.RAW.GATEWAY_RECEIPTS
FROM @HOOSIER_DATA.RAW.GATEWAY_STAGE
PATTERN = '.*detailedReceipts_20.*\.txt'
FILE_FORMAT = (TYPE='CSV' FIELD_DELIMITER='|' SKIP_HEADER=1
    NULL_IF=('') ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE)
ON_ERROR = 'CONTINUE';

-- Legacy bulk file
COPY INTO HOOSIER_DATA.RAW.GATEWAY_RECEIPTS_LEGACY
FROM @HOOSIER_DATA.RAW.GATEWAY_STAGE
PATTERN = '.*detailedReceipts_part.*\.txt'
FILE_FORMAT = (TYPE='CSV' FIELD_DELIMITER='|' SKIP_HEADER=1
    NULL_IF=('') ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE)
ON_ERROR = 'CONTINUE';

-- Township vendor year files (2020-2025)
COPY INTO HOOSIER_DATA.RAW.GATEWAY_TOWNSHIP_VENDOR
FROM @HOOSIER_DATA.RAW.GATEWAY_STAGE
PATTERN = '.*townshipDisburseByVendor_20.*\.txt'
FILE_FORMAT = (TYPE='CSV' FIELD_DELIMITER='|' SKIP_HEADER=1
    NULL_IF=('') ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE)
ON_ERROR = 'CONTINUE';

-- Township vendor legacy
COPY INTO HOOSIER_DATA.RAW.GATEWAY_TOWNSHIP_VENDOR_LEGACY
FROM @HOOSIER_DATA.RAW.GATEWAY_STAGE
PATTERN = '.*townshipDisburseByVendor\.txt'
FILE_FORMAT = (TYPE='CSV' FIELD_DELIMITER='|' SKIP_HEADER=1
    NULL_IF=('') ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE)
ON_ERROR = 'CONTINUE';

COPY INTO HOOSIER_DATA.RAW.GATEWAY_ECA_EXPENDITURES
FROM @HOOSIER_DATA.RAW.GATEWAY_STAGE
PATTERN = '.*eca_fund_expenditures.*\.txt'
FILE_FORMAT = (TYPE='CSV' FIELD_DELIMITER='|' SKIP_HEADER=1
    NULL_IF=('') ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE)
ON_ERROR = 'CONTINUE';

COPY INTO HOOSIER_DATA.RAW.GATEWAY_ECA_RECEIPTS
FROM @HOOSIER_DATA.RAW.GATEWAY_STAGE
PATTERN = '.*eca_fund_receipts.*\.txt'
FILE_FORMAT = (TYPE='CSV' FIELD_DELIMITER='|' SKIP_HEADER=1
    NULL_IF=('') ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE)
ON_ERROR = 'CONTINUE';

COPY INTO HOOSIER_DATA.RAW.GATEWAY_ECA_BALANCES
FROM @HOOSIER_DATA.RAW.GATEWAY_STAGE
PATTERN = '.*eca_fund_balances.*\.txt'
FILE_FORMAT = (TYPE='CSV' FIELD_DELIMITER='|' SKIP_HEADER=1
    NULL_IF=('') ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE)
ON_ERROR = 'CONTINUE';

-- WARNING: GATEWAY_TAX_DISTRIBUTIONS has no COPY_HISTORY — same risk as FORM4B.
-- Do NOT TRUNCATE in a reload script without confirming the source file is staged.
COPY INTO HOOSIER_DATA.RAW.GATEWAY_TAX_DISTRIBUTIONS
FROM @HOOSIER_DATA.RAW.GATEWAY_STAGE
PATTERN = '.*form22.*\.txt'
FILE_FORMAT = (TYPE='CSV' FIELD_DELIMITER='|' SKIP_HEADER=1
    NULL_IF=('') ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE)
ON_ERROR = 'CONTINUE';

COPY INTO HOOSIER_DATA.RAW.GATEWAY_ENTITY_FUNDS
FROM @HOOSIER_DATA.RAW.GATEWAY_STAGE
PATTERN = '.*e1_entity_funds.*\.txt'
FILE_FORMAT = (TYPE='CSV' FIELD_DELIMITER='|' SKIP_HEADER=1
    NULL_IF=('') ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE)
ON_ERROR = 'CONTINUE';

-- ── GATEWAY DETAIL TABLES (Bartholomew-filtered, comma-delimited CSV) ───────
-- Pre-process with scripts/prepare_gateway_data.ps1 first, then PUT the
-- upload_ready/ CSVs to GATEWAY_STAGE before running these.

COPY INTO HOOSIER_DATA.RAW.GATEWAY_DISBURSEMENTS_DETAIL
FROM @HOOSIER_DATA.RAW.GATEWAY_STAGE
PATTERN = '.*detailedDisburse_fundswithdept.*\.csv'
FILE_FORMAT = (TYPE='CSV' SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"'
    NULL_IF=('') ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE)
ON_ERROR = 'CONTINUE';

COPY INTO HOOSIER_DATA.RAW.GATEWAY_RECEIPTS_DETAIL
FROM @HOOSIER_DATA.RAW.GATEWAY_STAGE
PATTERN = '.*detailedReceipts.*\.csv'
FILE_FORMAT = (TYPE='CSV' SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"'
    NULL_IF=('') ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE)
ON_ERROR = 'CONTINUE';

COPY INTO HOOSIER_DATA.RAW.GATEWAY_FORM22
FROM @HOOSIER_DATA.RAW.GATEWAY_STAGE
PATTERN = '.*form22.*\.csv'
FILE_FORMAT = (TYPE='CSV' SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"'
    NULL_IF=('') ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE)
ON_ERROR = 'CONTINUE';

-- certNav is comma-delimited at source (no pipe conversion needed)
COPY INTO HOOSIER_DATA.RAW.GATEWAY_CERT_NAV
FROM @HOOSIER_DATA.RAW.GATEWAY_STAGE
PATTERN = '.*certNav.*\.csv'
FILE_FORMAT = (TYPE='CSV' SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"'
    NULL_IF=('') ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE)
ON_ERROR = 'CONTINUE';

-- ── GATEWAY NEW BULK TABLES (added 2026-06-08, pipe-delimited) ───────────────

COPY INTO HOOSIER_DATA.RAW.GATEWAY_CAP_ASSETS
FROM @HOOSIER_DATA.RAW.GATEWAY_STAGE
PATTERN = '.*afr_CapAssets.*\.txt'
FILE_FORMAT = (TYPE='CSV' FIELD_DELIMITER='|' SKIP_HEADER=1
    NULL_IF=('') ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE)
ON_ERROR = 'CONTINUE';

COPY INTO HOOSIER_DATA.RAW.GATEWAY_FORM4A
FROM @HOOSIER_DATA.RAW.GATEWAY_STAGE
PATTERN = '.*form4a.*\.txt'
FILE_FORMAT = (TYPE='CSV' FIELD_DELIMITER='|' SKIP_HEADER=1
    NULL_IF=('') ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE)
ON_ERROR = 'CONTINUE';

-- WARNING: FORM4B has no COPY_HISTORY — source file is not a routine stage drop.
-- Do NOT include this table in bulk TRUNCATE+reload templates without first confirming
-- the source file is actually staged. (See KAN-137.)
COPY INTO HOOSIER_DATA.RAW.GATEWAY_FORM4B
FROM @HOOSIER_DATA.RAW.GATEWAY_STAGE
PATTERN = '.*form4b.*'
FILE_FORMAT = (TYPE='CSV' FIELD_DELIMITER='|' SKIP_HEADER=1
    NULL_IF=('') ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE
    ENCODING = 'WINDOWS1252')
ON_ERROR = 'CONTINUE';

COPY INTO HOOSIER_DATA.RAW.GATEWAY_GRANTS
FROM @HOOSIER_DATA.RAW.GATEWAY_STAGE
PATTERN = '.*Grants.*\.txt'
FILE_FORMAT = (TYPE='CSV' FIELD_DELIMITER='|' SKIP_HEADER=1
    NULL_IF=('') ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE)
ON_ERROR = 'CONTINUE';

COPY INTO HOOSIER_DATA.RAW.GATEWAY_NONGOV_ENTITIES
FROM @HOOSIER_DATA.RAW.GATEWAY_STAGE
PATTERN = '.*nonGovEntities.*\.txt'
FILE_FORMAT = (TYPE='CSV' FIELD_DELIMITER='|' SKIP_HEADER=1
    NULL_IF=('') ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE)
ON_ERROR = 'CONTINUE';

COPY INTO HOOSIER_DATA.RAW.GATEWAY_TA7
FROM @HOOSIER_DATA.RAW.GATEWAY_STAGE
PATTERN = '.*TA7.*\.txt'
FILE_FORMAT = (TYPE='CSV' FIELD_DELIMITER='|' SKIP_HEADER=1
    NULL_IF=('') ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE)
ON_ERROR = 'CONTINUE';

COPY INTO HOOSIER_DATA.RAW.GATEWAY_DETAILED_REVENUE
FROM @HOOSIER_DATA.RAW.GATEWAY_STAGE
PATTERN = '.*detailedRevenue.*\.txt'
FILE_FORMAT = (TYPE='CSV' FIELD_DELIMITER='|' SKIP_HEADER=1
    NULL_IF=('') ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE)
ON_ERROR = 'CONTINUE';

COPY INTO HOOSIER_DATA.RAW.GATEWAY_CASH_INV_COMBINED
FROM @HOOSIER_DATA.RAW.GATEWAY_STAGE
PATTERN = '.*CashInvCombined.*\.txt'
FILE_FORMAT = (TYPE='CSV' FIELD_DELIMITER='|' SKIP_HEADER=1
    NULL_IF=('') ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE)
ON_ERROR = 'CONTINUE';

-- ── FEDERAL CONTRACTS ─────────────────────────────────────
-- Stage: CONTRACTS_STAGE
-- Files: Indiana-filtered CSVs from INDIANA_CONTRACTS folder
-- Pre-process with scripts/filter_indiana_contracts.py first

COPY INTO HOOSIER_DATA.RAW.FEDERAL_CONTRACTS
FROM @HOOSIER_DATA.RAW.CONTRACTS_STAGE
PATTERN = '.*\.csv'
FILE_FORMAT = (
    TYPE = 'CSV'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('')
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
)
ON_ERROR = 'CONTINUE';
